/**
 * @fileoverview gRPC-Web generated client stub for horoscope
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: astro.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.horoscope = require('./astro_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.horoscope.HoroscopeServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.horoscope.HoroscopeServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.horoscope.CalculateAstroRequest,
 *   !proto.horoscope.CalculateAstroResponse>}
 */
const methodDescriptor_HoroscopeService_CalculateAstro = new grpc.web.MethodDescriptor(
  '/horoscope.HoroscopeService/CalculateAstro',
  grpc.web.MethodType.UNARY,
  proto.horoscope.CalculateAstroRequest,
  proto.horoscope.CalculateAstroResponse,
  /**
   * @param {!proto.horoscope.CalculateAstroRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.horoscope.CalculateAstroResponse.deserializeBinary
);


/**
 * @param {!proto.horoscope.CalculateAstroRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.horoscope.CalculateAstroResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.horoscope.CalculateAstroResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.horoscope.HoroscopeServiceClient.prototype.calculateAstro =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/horoscope.HoroscopeService/CalculateAstro',
      request,
      metadata || {},
      methodDescriptor_HoroscopeService_CalculateAstro,
      callback);
};


/**
 * @param {!proto.horoscope.CalculateAstroRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.horoscope.CalculateAstroResponse>}
 *     Promise that resolves to the response
 */
proto.horoscope.HoroscopeServicePromiseClient.prototype.calculateAstro =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/horoscope.HoroscopeService/CalculateAstro',
      request,
      metadata || {},
      methodDescriptor_HoroscopeService_CalculateAstro);
};


module.exports = proto.horoscope;

