/**
 * @fileoverview gRPC-Web generated client stub for gateway
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: gateway.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.gateway = require('./gateway_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gateway.GatewayServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gateway.GatewayServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gateway.GetHoroscopeAnalysisRequest,
 *   !proto.gateway.GetHoroscopeAnalysisResponse>}
 */
const methodDescriptor_GatewayService_GetHoroscopeAnalysis = new grpc.web.MethodDescriptor(
  '/gateway.GatewayService/GetHoroscopeAnalysis',
  grpc.web.MethodType.UNARY,
  proto.gateway.GetHoroscopeAnalysisRequest,
  proto.gateway.GetHoroscopeAnalysisResponse,
  /**
   * @param {!proto.gateway.GetHoroscopeAnalysisRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gateway.GetHoroscopeAnalysisResponse.deserializeBinary
);


/**
 * @param {!proto.gateway.GetHoroscopeAnalysisRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gateway.GetHoroscopeAnalysisResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gateway.GetHoroscopeAnalysisResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gateway.GatewayServiceClient.prototype.getHoroscopeAnalysis =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gateway.GatewayService/GetHoroscopeAnalysis',
      request,
      metadata || {},
      methodDescriptor_GatewayService_GetHoroscopeAnalysis,
      callback);
};


/**
 * @param {!proto.gateway.GetHoroscopeAnalysisRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gateway.GetHoroscopeAnalysisResponse>}
 *     Promise that resolves to the response
 */
proto.gateway.GatewayServicePromiseClient.prototype.getHoroscopeAnalysis =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gateway.GatewayService/GetHoroscopeAnalysis',
      request,
      metadata || {},
      methodDescriptor_GatewayService_GetHoroscopeAnalysis);
};


module.exports = proto.gateway;

